adding:
  dependencies:
    config:
      - search_api.server.searchstax_server_1
  server: searchstax_server_1
removing:
  dependencies:
    config:
      - search_api.server.searchstax_server
  server: null
