adding:
  dependencies:
    config:
      - search_api.server.ddev_solr_local
  server: ddev_solr_local
removing:
  dependencies:
    config:
      - field.storage.node.field_subtext
      - search_api.server.searchstax_server
  field_settings:
    field_subtext:
      dependencies:
        config:
          - field.storage.node.field_subtext
      label: Subtext
      datasource_id: 'entity:node'
      property_path: field_subtext
      type: text
  processor_settings:
    html_filter:
      fields:
        - field_subtext
  server: null
