adding:
  dependencies:
    config:
      - search_api.server.ddev_solr_local
  server: ddev_solr_local
removing:
  dependencies:
    config:
      - search_api.server.searchstax_server_1
  server: null
