adding:
  dependencies:
    config:
      - search_api.server.ddev_solr_local
  server: ddev_solr_local
removing:
  dependencies:
    config:
      - search_api.server.searchstax_server
  field_settings:
  processor_settings:
    html_filter:
      fields:
        - field_subtext
  server: null
