adding:
  status: false
  dependencies:
    config:
      - search_api_solr.solr_cache.cache_document_default_9_0_0
      - search_api_solr.solr_cache.cache_fieldvalue_default_9_0_0
      - search_api_solr.solr_cache.cache_filter_default_9_0_0
      - search_api_solr.solr_cache.cache_persegfilter_default_9_0_0
      - search_api_solr.solr_cache.cache_queryresult_default_9_0_0
      - search_api_solr.solr_field_type.text_edge_und_7_0_0
      - search_api_solr.solr_field_type.text_edgestring_und_6_0_0
      - search_api_solr.solr_field_type.text_en_7_0_0
      - search_api_solr.solr_field_type.text_hi_7_0_0
      - search_api_solr.solr_field_type.text_ja_8_0_0
      - search_api_solr.solr_field_type.text_ngram_und_7_0_0
      - search_api_solr.solr_field_type.text_ngramstring_und_6_0_0
      - search_api_solr.solr_field_type.text_phonetic_en_7_0_0
      - search_api_solr.solr_field_type.text_phonetic_und_7_0_0
      - search_api_solr.solr_field_type.text_string_und_6_0_0
      - search_api_solr.solr_field_type.text_sv_7_0_0
      - search_api_solr.solr_field_type.text_und_7_0_0
      - search_api_solr.solr_request_dispatcher.request_dispatcher_httpcachingnever_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_autocomplete_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_extract_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_mlt_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_select_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_spell_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_suggest_default_7_0_0
      - search_api_solr.solr_request_handler.request_handler_tvrh_default_7_0_0
  description: "Connects to the <em class=\"placeholder\">WaterAid</em> SearchStax app (account <em class=\"placeholder\">WaterAid</em>).\r\n\r\nMigrated from the <em class=\"placeholder\">Acquia Search API Solr server</em> server."
  backend_config:
    connector_config:
      path: /
      timeout: 5
      index_timeout: 15
      optimize_timeout: 10
      finalize_timeout: 30
      skip_schema_check: false
      solr_version: ''
      http_method: AUTO
      commit_within: 1000
      jmx: false
      jts: false
      solr_install_dir: ''
removing:
  status: true
  description: |-
    Connects to the <em class="placeholder">WaterAid</em> SearchStax app (account <em class="placeholder">WaterAid</em>).

    Migrated from the <em class="placeholder">Acquia Search API Solr server</em> server.