field.value.wa_orange_dam_image:
  type: mapping
  label: Default value
  mapping:
    system_identifier:
      type: id
      label: System Identifier
    width:
      type: int
      label: Width
    height:
      type: int
      label: Height
